name: format check

on: [pull_request]

env:
  TERRAFORM_VERSION: 1.1.3

jobs:
  format-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: setup terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ TERRAFORM_VERSION }}

    - name: terraform format
      run: terraform fmt -recursive -check
